[features]
seeds = false
skip-lint = false
[programs.localnet]
r23_anchor_fe_pda_notes = "5yZW2zZ61P1rP56zH2obvcNQM6vPfiskPZXyWvWqz9zE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/vscode/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
